

export const UPDATE_LOADER = 'UPDATE_LOADER';
export const UPDATE_CREATE_MOVIE_MODAL = 'UPDATE_CREATE_MOVIE_MODAL';
export const SET_ACTORS = 'SET_ACTORS';
export const SET_PRODUCERS = 'SET_PRODUCERS';
export const REQUEST_UPLOAD_POSTER = 'REQUEST_UPLOAD_POSTER';
export const REQUEST_CREATE_MOVIE = 'REQUEST_CREATE_MOVIE';
export const REQUEST_ALL_MOVIE_SUCCESS = 'REQUEST_ALL_MOVIE_SUCCESS';
export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';


