

export const REQUEST_MOVIE = 'REQUEST_MOVIE';
export const OPEN_ADD_MOVIE_MODAL = 'OPEN_ADD_MOVIE_MODAL';
export const CLOSE_ADD_MOVIE_MODAL = 'CLOSe_ADD_MOVIE_MODAL';
export const SET_ACTORS = 'SET_ACTORS';
export const SET_PRODUCERS = 'SET_PRODUCERS';
export const REQUEST_UPLOAD_POSTER  = 'REQUEST_UPLOAD_POSTER';


